name = "drama-web"
pages_build_output_dir = "public"
compatibility_date = "2024-01-01"

# Database D1 (Tempat simpan permanen untuk Sitemap/RSS)
[[d1_databases]]
binding = "DB"
database_name = "dramabox-db"
database_id = "6a6d0cb2-3f20-45a1-b5a7-c83e6e86eec3"

# KV Namespace (Cache Cepat)
[[kv_namespaces]]
binding = "DRAMABOX_CACHE"
id = "3a391f2b8cc942df88db6870cdd84c69"
